[package]
name = "sniffer"
description = "Simple trafic analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
colored = "2.1"
pcap = "0.9"
serde_json = "1.0.140"
